export const COMMON_CONFIG_KEY = 'COMMON_CONFIG';
export const RELEASE_NAME_KEY = 'RELEASE_NAME';
export const RELEASE_PATH_KEY = 'RELEASE_PATH';
export const CURRENT_SERVER_CONFIG_KEY = 'CURRENT_SERVER_CONFIG';
export const PREVIOUS_RELEASE_NAME_KEY = 'PREVIOUS_RELEASE_NAME';
export const DEPLOYER_ACTION_KEY = 'DEPLOYER_ACTION';
export const SERVER_CONFIGS_KEY = 'SERVER_CONFIGS';
